### ISSUE TITLE
Hi, not rendering the foxbox background or corner borders.....

### ISSUE THREAD

**Issue by timfong888** [ihower/facebox_render#1]
I had to include prototype in addition to the jquery download to get it to run...but how do I get the graphical elements and the background to show.

The div tag shows and the css file shows as well, but not loading....

**Comment by ihower** [comment]
Try to put images files to /public/facebox/

**Comment by woto** [comment]
View errors through Firefox -> firebug extension

**Comment by MikeBinstock** [comment]
Some Images must be on javascript directory to work

**Comment by pcg79** [comment]
I changed all the css "background:url(png_file)" tags to:

background:url(../images/facebox/png_file)

to get it to work.
