### ISSUE TITLE
getting an method not allowed...

### ISSUE THREAD

**Issue by timfong888** [ihower/facebox_render#2]
Hi, I got it working for a regular page and then I created a restful route.  For some reason, it appears to be having problem.  Firebug is seeing it trying to load the right URL which does load, however, within Facebox.....

405 Method Not Allowed
  ActionController::MethodNotAllowed
Only get requests are allowed.

**Comment by ihower** [comment]
The default link_to_remote http method is POST, you can add :method => :get
e.g. link_to_remote 'foo', :url => bar_path, :method => :get
